### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by NuMiCo** [banjtheman/highwind#1]
Thank you for the great job - I liked it very much. Please explain how to transfer a contract from testnet content to mainnet content. We tried it with different methods, but it doesn’t work. 
Best regards

**Comment by banjtheman** [comment]
Hey thanks for the feedback!! I just pushed code that will allow you to deploy contracts to the Polygon and Ethereum Mainnet. This does use real funds so be careful

**Comment by NuMiCo** [comment]
Thanks for a great job. 
Please tell me for a beginner - when creating a contract for a Ethereum minnet, how much will the cost of creating a contract and how much is the cost of creating a every token for a mainnet in Ethereum?
Thanks in advance for the information
